import InfoPage, { InfoSection } from "@/components/landing/InfoPage";

export const metadata = { title: "Terms & Conditions | VOCA" };

export default function TermsPage() {
  return (
    <InfoPage
      title="Terms & Conditions"
      tagline="The short, readable version of the rules for using VOCA."
      updated="July 25, 2026"
    >
      <InfoSection heading="1. Accepting these terms">
        <p>
          By creating an account or using VOCA you agree to these terms. If you do not
          agree with them, please do not use the service.
        </p>
      </InfoSection>
      <InfoSection heading="2. Your account">
        <p>
          You are responsible for your account and for keeping your password safe. You
          must provide accurate information when registering, and you must be old
          enough to hold an account under the laws that apply to you.
        </p>
      </InfoSection>
      <InfoSection heading="3. Acceptable use">
        <p>
          VOCA is for personal vocabulary learning. You agree not to abuse the service:
          no attempts to break or overload it, no scraping other users&apos; data, no
          using the AI chat for anything unlawful, and no reselling access.
        </p>
      </InfoSection>
      <InfoSection heading="4. Your content">
        <p>
          The words, notes, and messages you add remain yours. You give us permission
          to store and process them so the service can work, for example scheduling
          reviews and generating AI answers about your words.
        </p>
      </InfoSection>
      <InfoSection heading="5. AI-generated content">
        <p>
          Definitions, examples, and chat replies may be generated by an AI model.
          They are provided for learning purposes and may occasionally be inaccurate.
          Use your own judgement before relying on them.
        </p>
      </InfoSection>
      <InfoSection heading="6. Ending your account">
        <p>
          You can delete your account at any time from Settings, which permanently
          removes your data. We may suspend accounts that violate these terms.
        </p>
      </InfoSection>
      <InfoSection heading="7. Warranty and liability">
        <p>
          VOCA is provided as is, without warranties of any kind. To the extent the law
          allows, we are not liable for indirect damages arising from your use of the
          service.
        </p>
      </InfoSection>
      <InfoSection heading="8. Changes">
        <p>
          We may update these terms as the product evolves. If a change is
          significant, we will make it visible in the app. Continuing to use VOCA
          after a change means you accept the new terms.
        </p>
      </InfoSection>
      <InfoSection heading="9. Contact">
        <p>
          Questions about these terms? Reach out through the project&apos;s GitHub page:{" "}
          <a
            href="https://github.com/PulkitGarg31"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent hover:underline"
          >
            github.com/PulkitGarg31
          </a>
          .
        </p>
      </InfoSection>
    </InfoPage>
  );
}
